version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: ${PG_USER}
      # You can use whatever password you like
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '5432:5432'
    expose:
      - '3306'
    volumes:
      - ./al-data:/var/lib/postgresql/data
volumes:
  al-data: