import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Wrapper } from '../hoc/Layout/Layout';
import { MainView } from '../components/MainPage/MainView';
import { prisma } from '../../lib/prisma';
import { GetStaticProps } from 'next';

export default function Home() {
  export async function loadAuthors() {
    const res = await fetch[Symbol]();
  }
  console.log(authors);
  return (
    <>
      <Head>
        <title>Awesome Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <MainView />
      </Wrapper>
    </>
  );
}
