import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from 'src/styles/Home.module.css';
import { Wrapper } from '../hoc/Layout/Layout';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Awesome Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <h1>Pieprzone więcej</h1>
      </Wrapper>
    </>
  );
}
