import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Wrapper } from '../hoc/Layout/Layout';
import { MainView } from '../components/MainPage/MainView';
// import { prisma } from '../../lib/prisma';
import { GetStaticProps } from 'next';
import { PrismaClient } from '@prisma/client';
import { env } from 'process';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: 'postgresql://postgres:dupadupa@localhost:5432/postgres?schema=public',
    },
  },
});
export const getStaticProps = async () => {
  const feed = await prisma.author.findMany();
  return {
    props: { feed },
  };
};
export default function Home({ feed }: { feed: any }) {
  feed && console.log(feed);
  return (
    <>
      <Head>
        <title>Awesome Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <MainView />
      </Wrapper>
    </>
  );
}
